# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
          - id: check-ast
          - id: check-toml
          - id: requirements-txt-fixer

    - repo: https://github.com/asottile/reorder-python-imports
      rev: v3.10.0
      hooks:
          - id: reorder-python-imports
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v3.0.0-alpha.9-for-vscode"
      hooks:
          - id: prettier
            types: [json]

    - repo: https://github.com/psf/black
      rev: 23.3.0
      hooks:
          - id: black-jupyter
            # It is recommended to specify the latest version of Python
            # supported by your project here, or alternatively use
            # pre-commit's default_language_version, see
            # https://pre-commit.com/#top_level-default_language_version
            language_version: python3.11
