experiment:
    name: SNER Solo
    folds: 10
    random_state: 125
    precision_average: "weighted"
    recall_average: "weighted"

dataset:
    name: forum

mlflow:
    tracking_uri: "http://127.0.0.1:5000"

defaults:
    - _self_
    - transformation: all

    - override hydra/launcher: joblib
    - override hydra/job_logging: colorlog
    - override hydra/hydra_logging: colorlog

hydra:
    launcher:
        n_jobs: 3
    sweeper:
        params:
            dataset.name: forum,prolific,all
            transformation: "glob(*)"
