experiment:
    name: SNER Solo
    folds: 10
    random_state: 125
    precision_average: "weighted"
    recall_average: "weighted"

dataset:
    name: forum

transformation:
    task:
    goals:
    domain_data:
    activity:
    stakeholder:
    system_function:
    interaction:
    interaction_data:
    workspace:
    software:
    internal_action:
    internal_data:

mlflow:
    tracking_uri: "http://127.0.0.1:5000"
