experiment:
    name: SNER Solo
    test_size: 0.2
    random_state: 125

dataset:
    name: forum

transformation:
    task:
    goals:
    domain_data:
    activity:
    stakeholder:
    system_function:
    interaction:
    interaction_data:
    workspace:
    software:
    internal_action:
    internal_data:

mlflow:
    tracking_uri: "http://127.0.0.1:5000"
