defaults:
    - base_config
    - transformation: levels

    - override hydra/launcher: joblib
    - override hydra/job_logging: colorlog
    - override hydra/hydra_logging: colorlog

    - _self_

experiment:
    name: BERT Test
    dataset: prolific
    lower_case: True

bert:
    model: bert-base-uncased
    max_len:
    train_batch_size: 32
    validation_batch_size: 8
    number_epochs: 5
    learning_rate: 5e-05
    weight_decay: 0.01
    weighted_classes: True

hydra:
    launcher:
        n_jobs: 1
    sweeper:
        params:
