defaults:
    - base_config
    - transformation: none
    - hint_transformation: levels

    - override hydra/launcher: joblib
    - override hydra/job_logging: colorlog
    - override hydra/hydra_logging: colorlog

    - _self_

experiment:
    name: StagedBERT Test
    dataset: prolific
    iterations: 1
    force: False

bert:
    model: bert-base-uncased
    max_len:
    train_batch_size: 32
    validation_batch_size: 64
    number_epochs: 1
    weight_decay: 0
    weighted_classes: True
    learning_rate_bert: 2e-05
    learning_rate_classifier: 0.01
    layers:
        - 10
        - 20
        - 30

hydra:
    launcher:
        n_jobs: 1
    sweeper:
        params:
            experiment.name: StagedBERT Test
            experiment.dataset: prolific, all
            bert.layers: "[10,10],[10,11],[11,10]"
