defaults:
    - base_config
    - transformation: none

    - override hydra/launcher: joblib
    - override hydra/job_logging: colorlog
    - override hydra/hydra_logging: colorlog

    - _self_

experiment:
    name: BERT Test
    dataset: prolific

bert:
    max_len:
    train_batch_size: 64
    validation_batch_size: 8
    number_epochs: 10
    learning_rate: 2e-05
    weight_decay: 0.01
    weighted_classes: True

hydra:
    launcher:
        n_jobs: 1
    sweeper:
        params:
            experiment.name: BERT Test
            experiment.dataset: prolific
            transformation: none
            bert.weighted_classes: False,True
