experiment:
    name: SNER Solo
    folds: 5
    random_state: 125
    average: "macro"
    dataset: forum

transformation: None

meta:
    mlflow_tracking_uri: "https://bockstaller.cc"

defaults:
    - _self_
    - transformation: None

    - override hydra/launcher: joblib
    - override hydra/job_logging: colorlog
    - override hydra/hydra_logging: colorlog

hydra:
    launcher:
        n_jobs: 4
    sweeper:
        params:
            experiment.dataset: forum,prolific,all
            transformation: "glob(*)"
