defaults:
    - base_config
    - transformation: none
    - hint_transformation: levels

    - override hydra/launcher: joblib
    - override hydra/job_logging: colorlog
    - override hydra/hydra_logging: colorlog

    - _self_

experiment:
    name: StagedBERT Test
    dataset: prolific

bert:
    model: bert-base-uncased
    max_len:
    train_batch_size: 32
    validation_batch_size: 64
    number_epochs: 32
    learning_rate: 2e-05
    weight_decay: 0
    weighted_classes: True

hydra:
    launcher:
        n_jobs: 1
    sweeper:
        params:
            experiment.name: StagedBERT Solo
            experiment.dataset: forum,prolific,all
            transformation: "glob(*)"
