defaults:
    - base_config
    - transformation: none

    - override hydra/launcher: joblib
    - override hydra/job_logging: colorlog
    - override hydra/hydra_logging: colorlog

    - _self_

experiment:
    name: BiLSTM Test
    dataset: prolific

bilstm:
    sentence_length:
    batch_size: 64
    learning_rate: 0.01
    number_epochs: 20
    verbose: 2
    weighted_classes: True

hydra:
    launcher:
        n_jobs: 8
    sweeper:
        params:
            bilstm.weighted_classes: False,True
