experiment:
    name: BiLSTM Solo
    folds: 5
    random_state: 125
    average: "macro"
    dataset: forum

transformation: all

bilstm:
    sentence_length:
    batch_size: 32
    number_epochs: 50
    validation_split: 0.1
    verbose: 1

meta:
    mlflow_tracking_uri: "http://127.0.0.1:5000"

defaults:
    - _self_
    - transformation: all

    - override hydra/launcher: joblib
    - override hydra/job_logging: colorlog
    - override hydra/hydra_logging: colorlog

hydra:
    launcher:
        n_jobs: 4
    sweeper:
        params:
            experiment.dataset: forum,prolific,all
            transformation: "glob(*)"
