defaults:
    - base_config
    - transformation: label_activity

    - override hydra/launcher: joblib
    - override hydra/job_logging: colorlog
    - override hydra/hydra_logging: colorlog

    - _self_

experiment:
    name: BERT Test
    dataset: forum

bert:
    max_len:
    train_batch_size: 32
    validation_batch_size: 8
    number_epochs: 5
    learning_rate: 2e-05
    weight_decay: 0.01

hydra:
    launcher:
        n_jobs: 1
    sweeper:
        params:
            experiment.name: BERT Solo
            experiment.dataset: forum,prolific,all
            transformation: "glob(*)"
