defaults:
    - base_config
    - transformation: none

    - override hydra/launcher: joblib
    - override hydra/job_logging: colorlog
    - override hydra/hydra_logging: colorlog

    - _self_

experiment:
    name: BiLSTM Test
    dataset: prolific

algorithm:
    sentence_length:
    batch_size: 32
    number_epochs: 10
    validation_split: 0.1
    verbose: 1

hydra:
    launcher:
        n_jobs: 8
    sweeper:
        params:
            experiment.dataset: forum,prolific,all
            transformation: "glob(*)"
