experiment:
    name: BiLSTM Parameter Sweep
    folds: 5
    random_state: 125
    average: "macro"
    dataset: prolific

transformation: None

bilstm:
    sentence_length:
    batch_size: 32
    number_epochs: 10
    validation_split: 0.1
    verbose: 1

meta:
    mlflow_tracking_uri: "https://bockstaller.cc"

defaults:
    - _self_
    - transformation: levels

    - override hydra/launcher: joblib
    - override hydra/job_logging: colorlog
    - override hydra/hydra_logging: colorlog

hydra:
    launcher:
        n_jobs: 8
    sweeper:
        params:
            experiment.dataset: prolific
            bilstm.batch_size: 8,16,24,32,64
            bilstm.number_epochs: 10,20,30,40,50
            transformation: "none"
            experiment.folds: 5
            bilstm.validation_split: 0.01,0.05,0.1
