defaults:
    - base_config
    - transformation: none
    - transformation@first_model_sner.transformation: levels

    - override hydra/launcher: joblib
    - override hydra/job_logging: colorlog
    - override hydra/hydra_logging: colorlog

    - _self_

experiment:
    name: Dual Model StagedBERT Test
    dataset: prolific
    iterations: 1
    force: True

first_model_sner:
    experiment:
        name: SNER Test
        dataset: prolific
        lower_case: True
        force: True
        iterations: 1

bert:
    model: bert-base-uncased
    max_len:
    train_batch_size: 8
    validation_batch_size: 64
    number_epochs: 10
    weight_decay: 0.01
    weighted_classes: True
    learning_rate_bert: 3e-05
    learning_rate_classifier: 0.1
    layers:
        - 1

hydra:
    launcher:
        n_jobs: 1
    sweeper:
        params:
            experiment.name: Dual Model StagedBERT Test
            experiment.dataset: prolific, all

            force: False
